---
- hosts: all
  vars_prompt:
    - name: wg_ui_password
      prompt: "Enter WireGuard UI password"
      private: yes  # This ensures the input is not displayed

  vars:
    # WG-Easy domain name
    domain: $domain
    # Whitelisted IP's
    allowed_ips: 0.0.0.0/0
    password: "{{ wg_ui_password }}"

  become: yes
  tasks:

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.1/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
        dest: "/usr/local/bin/docker-compose"
        mode: 'u+x,g+x'
        force: yes

    - name: Render docker-compose.yaml template
      template:
        src: templates/docker-compose.yaml.j2
        dest: /opt/docker-compose.yaml

    - name: Render wg-easy.conf template
      template:
        src: templates/wg-easy.conf.j2
        dest: /opt/wg-easy.conf

    - name: Deploy wg-easy using docker-compose
      command: /usr/local/bin/docker-compose -f /opt/docker-compose.yaml up -d
      args:
        chdir: /opt/

    - name: Create SSH Certificate
      environment:
        DOMAIN: $domain
      shell: |
        docker cp /opt/wg-easy.conf nginx:/etc/nginx/conf.d/.
        docker exec -it nginx /bin/sh -c "
        certbot --nginx --non-interactive --agree-tos -m webmaster@google.com -d $DOMAIN
        "
