---
- hosts: all
  vars:
    # WG-Easy domain name
    domain: <wg-easy.domain.com>
    # WG-Easy UI password
    password: <pw>
    # Whitelisted IP's
    allowed_ips: 0.0.0.0/0

  become: yes
  tasks:

    - name: Install Docker Compose (CentOS/RHEL)
      yum:
        name: docker-compose
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Install Docker Compose (Debian/Ubuntu)
      apt:
        name: docker-compose
        state: latest
      when: ansible_os_family == "Debian"

    - name: Render docker-compose.yaml template
      template:
        src: templates/docker-compose.yaml.j2
        dest: /opt/docker-compose.yaml

    - name: Render wg-easy.conf template
      template:
        src: templates/wg-easy.conf.j2
        dest: /opt/wg-easy.conf

    - name: Deploy wg-easy using docker-compose
      command: docker-compose -f /opt/docker-compose.yaml up -d
      args:
        chdir: /opt/

    - name: Create SSH Certificate
      environment:
        DOMAIN: "{{ domain }}"
      shell: |
        docker cp /opt/wg-easy.conf nginx:/etc/nginx/conf.d/.
        docker exec -it nginx /bin/sh -c "
        certbot --nginx --non-interactive --agree-tos -m webmaster@google.com -d $DOMAIN
        "
